export const config = {
  baseUrl: "https://random-backend.digitalcodemasters.info",
  login: "/auth/login",
  register: "/auth/register",
  update: "/auth/update",
  details: "/auth/details",
  category: "/category",
  saveInterest: "/auth/updateInterest",
  skipInterest: "/auth/skipInterest",
  asset: "/asset/random/asset",
  puzzle: "/puzzle/random",
  suggestStatement: "/commitmentandstatement/statement",
  suggestCommitment: "/commitmentandstatement/commitment",
  assignCommitment: "/commitmentandstatement/commitment",
  assignStatement: "/commitmentandstatement/statement",
  commitments: "/commitmentandstatement/user/commitment",
  notifications: "/asset/share",
  assetWithId: "/asset",
  shareAsset: "/asset/share",
  shareCommitment: "/asset/share/commitment",
  completeCommitment: "/commitmentandstatement/complete",
};
